# Foundation application configuration
app-name = "Calculator"
friendly-app-name = "Calculator"
launcher-app-name = "Calculator"
description = "Fast basic and scientific calculator"
icon = "resources/icon.svg"
theme = "theme/theme.json"
app-id = "0x78be76408256ad1808ea89b7c0a61fc9"
version = "0.1.0"
min-keyos-version = "1.0.0"
signing-identity = "passport-prime-dev"

[publisher]
name = "Foundation Devices, Inc."
contact-email = "hello@foundation.xyz"
support-url = "https://foundation.xyz"

[permissions]
template = ["gui-app"]
